spring: 
 profiles:
  active:
  -dev

---
spring: 
 profiles: dev
 application:
  name: microservicecloud-config-atguigu-dev
		
---
spring:
 profiles: test
 application:
  name: microservicecloud-config-atguigu-test
  profiles: 
   active: 
   - dev

---
spring: 
 profiles: dev 
 application: 
  name: microservicecloud-config-atguigu-dev

---
spring:
 profiles: test 
 application: 
  name: microservicecloud-config-atguigu-test

